### ISSUE TITLE
Advanced search - select fields on which to search

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#460]
Somehow allow users to constrain their search to certain fields of an item:
- title
- institution (difficult to handle alt. names)
- access points
- identifier

Question: how to do this without cluttering the interface?

**Comment by retosp** [comment]
Let's just beef up the tips we provide if a user clicks on the "advanced query tipps". We whould do this asap so that the text can be translated. Currently, we have this text:

"
There are several ways to be more specific in your search query:

"Phrase"
    Search an exact match of your query, e.g. "Member lists"
+Phrase
    Given word has to be in the result, e.g. +Gestapo
-Phrase
    Exclude given word from search, e.g. -Gestapo "
"

We could change it to something like this:
"
There are several ways to be more specific in your search query.

Use the following syntax to exclusively search through the titles or identifiers of descriptions:

title:”phrase”    For instance, you can find all descriptions that have the phrase “Auschwitz Birkenau” in their titles by searching for title:”Auschwitz Birkenau” .
 
identifier:identifier    This is useful if you already know the local identifier of a description. For instance, the query identifier:irn502192 will return the description of the collection “KL Auschwitz-Birkenau” of the United States Holocaust Memorial Museum (USHMM) that is identified at the USHMM by “irn502192”.

In addition, the following operators can be used to render your searches more specific:

"Phrase"    Search an exact match of your query, e.g. "Concentration Camp"
+Phrase    Given word has to be in the result, e.g. +Gestapo
-Phrase    Exclude given word from search, e.g. -Gestapo
"

**Comment by mikesname** [comment]
Thanks! I wanted to obviate this by adding a UI field switcher, but that's one of those ludicrous jobs that will probably take me about 1 day per line of CSS. It does need to be done though since you can also now select by:

 - subject (or keyword)
 - creator (or author)
 - place (or location)
 - person
