### ISSUE TITLE
Guides: link to the guide from the archival descriptions in the portal

### ISSUE THREAD

**Issue by michalfrankl** [EHRI/ehri-frontend#530]
Archival descriptions in the portal that are part of one of the guides should include a clearly visible information about this and a link to the guide.

**Comment by michalfrankl** [comment]
I'd like to come back to this - the unit description in the portal interface should include a link to guides/virtual collections in which it's included - at least those that were created by EHRI.

**Comment by mikesname** [comment]
Going forward for EHRI 2 and the re-working we need to do, I think we should consider using something like [trackbacks](http://en.wikipedia.org/wiki/Trackback) for this. It's going to require a bit of thought, since I want to completely separate the guides from the portal (as a codebase) so they can flourish independently and on a different timescale.

**Comment by michalfrankl** [comment]
We'll discuss the separation and its alternatives separately, but it should be clear that the data is always part of the database and of the portal. While I'm not against trackbacks or somethink like this, I'd like to have a link to the record in the guide in place quickly, since the guides need to be advertised in some way.
