### ISSUE TITLE
Layout in Authoritative Sets / Vocabularies views...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#56]
These don't seem to match the layouts of other article/sidebar pages and I'm not sure why. There is less margin on the main content.

**Comment by ixt** [comment]
Still exists in redesign. I think this is due to the side-bar being being kept in the section with item-details main and not with the results apart from the results. I see this in Firefox and Chrome on desktop. Moving the sidebar to be in search-results inside of the form makes the page look better. The item details main still looks odd but not as odd as before.
